version: "3.8"
services:
  frontend:
    image: node:18
    container_name: vite_app
    working_dir: /app
    volumes:
      - .:/app  # Mount your project folder
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
